[package]
name = "datchani"
version = "0.1.0"
edition = "2021"
description = "A Certain Magical Indexer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
